version: '3.1'

services:
  test-task-application:
    build: .
    ports:
      - "8080:8080"
    image: sdet-task-1
    command:
      - "java"
      - "-jar"
      - "sdet-task.jar"

  e2e-tests:
    image: sdet-task-1
    command:
      - "./gradlew"
      - "cleanTest"
      - "test"
    environment:
      APP_URL: http://test-task-application:8080
      APP_DB_HOST: db
      APP_DB_USER: john
      APP_DB_PASSWORD: mysecretpassword
    depends_on:
      - test-task-application